### ISSUE TITLE
Missing Submodule

### ISSUE THREAD

**Issue by JonTheNiceGuy** [radiantbluetechnologies/ossim-vagrant#2]
Hi, just tried to use this, and found your submodule sm-rtbcloud-com (which points to https://github.com/radiantbluetechnologies/sm-rbtcloud-com) doesn't work any more.

All the best,

Jon

**Comment by benhosmer** [comment]
That repo is private. That's the reason you weren't able to access it. Let me talk it over with some of my coworkers and see if maybe we can make the repo public.

**Comment by JonTheNiceGuy** [comment]
Ha, that makes sense! :)

No worries if you can't, I was just looking for a vagrant-able OSSIM image, as that's how all my home infrastructure is stood up.

**Comment by benhosmer** [comment]
Are you just interested in working with OSSIM, or do you need OMAR
functionality too?

On Thu, Aug 13, 2015 at 7:14 AM, JonTheNiceGuy <notifications@github.com>
wrote:

> Ha, that makes sense! :)
>
> No worries if you can't, I was just looking for a vagrant-able OSSIM
> image, as that's how all my home infrastructure is stood up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiantbluetechnologies/ossim-vagrant/issues/2#issuecomment-130622560>
> .
>



-- 
Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by JonTheNiceGuy** [comment]
OSSIM alone for the mo.

--
Jon "The Nice Guy" Spriggs

**Comment by benhosmer** [comment]
Okay, let me see what I can do for you.

On Thu, Aug 13, 2015 at 7:25 AM, JonTheNiceGuy <notifications@github.com>
wrote:

> OSSIM alone for the mo.
>
> --
> Jon "The Nice Guy" Spriggs
>
> On 13 August 2015 at 12:23, Ben Hosmer <notifications@github.com> wrote:
>
> > Are you just interested in working with OSSIM, or do you need OMAR
> > functionality too?
> >
> > On Thu, Aug 13, 2015 at 7:14 AM, JonTheNiceGuy <notifications@github.com
> >
> > wrote:
> >
> > > Ha, that makes sense! :)
> > >
> > > No worries if you can't, I was just looking for a vagrant-able OSSIM
> > > image, as that's how all my home infrastructure is stood up.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/radiantbluetechnologies/ossim-vagrant/issues/2#issuecomment-130622560
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Ben Hosmer
> >
> > Brevard Tech - Brevard County Florida's Tech User Group
> > http://www.brevardtech.org
> >
> > Drupal Developer
> > http://www.radarearth.com
> >
> > 321.252.9581
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/radiantbluetechnologies/ossim-vagrant/issues/2#issuecomment-130627996
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiantbluetechnologies/ossim-vagrant/issues/2#issuecomment-130628318>
> .
>



-- 
Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by benhosmer** [comment]
I haven't forgotten about this. I'll hopefully get it in a somewhat
workable state for you by the weekend at the latest.

On Thu, Aug 13, 2015 at 7:34 AM, Ben Hosmer <ben.hosmer@gmail.com> wrote:

> Okay, let me see what I can do for you.
>
> On Thu, Aug 13, 2015 at 7:25 AM, JonTheNiceGuy <notifications@github.com>
> wrote:
>
>> OSSIM alone for the mo.
>>
>> --
>> Jon "The Nice Guy" Spriggs
>>
>> On 13 August 2015 at 12:23, Ben Hosmer <notifications@github.com> wrote:
>>
>> > Are you just interested in working with OSSIM, or do you need OMAR
>> > functionality too?
>> >
>> > On Thu, Aug 13, 2015 at 7:14 AM, JonTheNiceGuy <
>> notifications@github.com>
>> > wrote:
>> >
>> > > Ha, that makes sense! :)
>> > >
>> > > No worries if you can't, I was just looking for a vagrant-able OSSIM
>> > > image, as that's how all my home infrastructure is stood up.
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> >
>> https://github.com/radiantbluetechnologies/ossim-vagrant/issues/2#issuecomment-130622560
>> > >
>> > > .
>> > >
>> >
>> >
>> >
>> > --
>> > Ben Hosmer
>> >
>> > Brevard Tech - Brevard County Florida's Tech User Group
>> > http://www.brevardtech.org
>> >
>> > Drupal Developer
>> > http://www.radarearth.com
>> >
>> > 321.252.9581
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/radiantbluetechnologies/ossim-vagrant/issues/2#issuecomment-130627996
>> >
>>
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/radiantbluetechnologies/ossim-vagrant/issues/2#issuecomment-130628318>
>> .
>>
>
>
>
> --
> Ben Hosmer
>
> Brevard Tech - Brevard County Florida's Tech User Group
> http://www.brevardtech.org
>
> Drupal Developer
> http://www.radarearth.com
>
> 321.252.9581
>



-- 
Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by JonTheNiceGuy** [comment]
That would be awesome! Thank you!

**Comment by benhosmer** [comment]
@JonTheNiceGuy Are you using windows by chance? I assume since you're a fairly experienced vagrant user you'll be able to get around the NFS settings we have in our Vagrantfile.

**Comment by benhosmer** [comment]
@JonTheNiceGuy I've updated our master branch with an ossim only feature. I notated how to do it in the README. Let me know if this gets you were you want to be and if we can close this issue out.

**Comment by JonTheNiceGuy** [comment]
Wow, that's awesome (and mildly worrying I didn't spot it was technically that simple!)

Yes, it's perfect. I'll give it a whirl, and re-open this if there's anything outstanding.

You rock :D

**Comment by benhosmer** [comment]
OSSIM is a bear to install from source and you probably would have had a
hard time finding the repo on your own.

Thanks!

On Fri, Aug 21, 2015 at 11:26 AM, JonTheNiceGuy <notifications@github.com>
wrote:

> Closed #2
> <https://github.com/radiantbluetechnologies/ossim-vagrant/issues/2>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiantbluetechnologies/ossim-vagrant/issues/2#event-388914943>
> .
>



-- 
Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581
